[package]
name = "remote_shellcode"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser","handleapi","memoryapi","errhandlingapi","processthreadsapi","winnt","synchapi"] }