[package]
name = "shellcode_winapi"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser","memoryapi","errhandlingapi","processthreadsapi","winnt","synchapi"] }